const QUESTOES = [
    {num:1,
     Q:"O que é JSX?",
     B: false,
     cor: "#333333",
     R:"Uma extensão de linguagem do JavaScript"},
    {num:2,
    Q:"O React é __ ",
    B: false,
    cor: "#333333",
    R:"uma biblioteca JavaScript para construção de interfaces"},
    {num:3,
    Q: "Componentes devem iniciar com __ ",
    B: false,
    cor: "#333333",
    R:"letra maiúscula"},
    {num:4,
    Q:"Podemos colocar __ dentro do JSX",
    B: false,
    cor: "#333333",
    R:"expressões"},
    {num:5,
    Q:"O ReactDOM nos ajuda __ ",
    B: false,
    cor: "#333333",
    R:"interagindo com a DOM para colocar componentes React na mesma"},
    {num:6,
    Q:"Usamos o npm para __ ",
    B: false,
    cor: "#333333",
    R:"gerenciar os pacotes necessários e suas dependências"},
    {num:7,
    Q:"Usamos props para __ ",
    B: false,
    cor: "#333333",
    R:"passar diferentes informações para componentes"},
    {num:8,
    Q:"Usamos estado (state) para __ ",
    B: false,
    cor: "#333333",
    R:"dizer para o React quais informações quando atualizadas devem renderizar a tela novamente"}
]

export default QUESTOES